require('./swagger/swagger-plugin')
require('./asyncapi/asyncapi-plugin')
require('./markdown/markdown-plugin')
require('./tiptap/tiptap-plugin')
require('./tinyeditor/tinyeditor-plugin')
require('./editorjs/editorjs-plugin')
require('./quill/quill-plugin')
// require('./bpmn/bpmn-plugin')
