# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'    
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Build plugins
      run: npm run build --if-present
#    - name: Upload to demo repository
#      uses: cpina/github-action-push-to-another-repository@v1.3
#      env:
#        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#      with:
#        source-directory: 'dist'
#        destination-repository-name: 'drawio'
    - name: Release
      uses: docker://antonyurchenko/git-release:latest
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "true"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "none"
        ALLOW_EMPTY_CHANGELOG: "true"
        ALLOW_TAG_PREFIX: "false"
      with:
        args: |
            dist/*
